// src/integrations/supabase/client.ts
// --- DO NOT EDIT THIS FILE DIRECTLY UNLESS CHANGING CONFIG ---

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Ensure environment variables exist
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Supabase environment variables missing. Please check your .env file.');
  throw new Error('Supabase credentials are missing.');
}

// Create and export the Supabase client
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: { 'x-client-info': 'onboarding-chatbot' },
    },
  }
);
